// import { api } from '~/utils/api'
import Head from 'next/head'

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: 'from tRPC' })
  // const routes = api.botConfig.getRoutes.useQuery()
  // const profiles = api.botConfig.getProfiles.useQuery()
  // const models = api.botConfig.getModels.useQuery()
  // const options = api.botConfig.getOptions.useQuery()

  return (
    <>
      <Head>
        <title>pIRCe</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center base-content">
        <div className="container flex flex-col items-center justify-center gap-6 px-4 py-16">
          <h1 className="prose">pIRCe dashboard</h1>
          <p>Coming in 2024</p>
        </div>
      </main>
    </>
  )
}
